language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: TOLwlOQ0N/zdfcXnHRu52AfiuGQaBOwEt+b1xJKQ7Npmpn900WPP3BL5z3urpcgaPGGcaBRMm90X8lDk78gmOGL8GERGtNQhKpGDpDHvUOcD+ENJVX19SDjdu1ix8WEDhDS7N4l6rxcjTyACPxHthSTkAWN9uynPc19ClnnceYrKHfPnJQ1lmUdq3JyeQCV3CNeX0plR+aMn9IpX30p1tSjeChuRVMRp0mGoD7FctRcqtt96M0pJfGpsIBQqjHXNxLJZTxEmoHNpL1TSKYCpXoUhmpSi72ED3fYZT1FMxispz8/+7+0vFxqOLGo7K8uoPpe+IdOZquhvs0BMsObE3K0Ukr62bgT+dv1+7JaKAzuyHUyEjA9UQdSdGhEXPbSkJgD07B5iFpPAkm5bbwmyk+PXcUm2kvZv99R7xnHJt2qin3z1lX/zdg2yqO7nfnaAJnujN85TtidW/nxOhzg6jJkm+zOkmbjNk5iL5OXJsQALM2EYTdpgn/6lH7KOE5c9MtIENF/BJYVj/3ganFq3Ej27LyozTTm5dRQtxhaR4NAR907296ZrIec/1Dy1nEw6xilDAULX7RCpbSXdEXwQwe9KhdQrKfH9LPgmWNgjW7KKePTysJQj2QGB7vfMifrLftI9VTv9tR/cjQJHuuFO4P8Pz05+M4FKzAvODS9qav8=
  app: mxsdb
  on:
    repo: aaronr5/mxs-content-site
